export function GoodsMarket() {
  const categories = [
    {
      name: 'Spices & Aromatics',
      icon: '🌶️',
      items: [
        { good: 'Black Pepper', origin: 'Malabar Coast, Kerala', value: 'Worth its weight in gold', info: 'Most prized spice in ancient Rome; Indian monopoly on production' },
        { good: 'Cardamom', origin: 'Western Ghats, India', value: 'Queen of Spices', info: 'Expensive aromatic spice used in medicine and cooking' },
        { good: 'Cinnamon', origin: 'Southern India & Sri Lanka', value: 'Extremely Valuable', info: 'Sacred spice used in religious ceremonies and royal courts' },
        { good: 'Turmeric', origin: 'Indian Subcontinent', value: 'Golden Spice', info: 'Used in medicine, cooking, and religious rituals' }
      ]
    },
    {
      name: 'Textiles & Dyes',
      icon: '🧵',
      items: [
        { good: 'Cotton Muslin', origin: 'Bengal & Dhaka', value: 'Woven Air', info: 'So fine it could pass through a ring; prized across the world' },
        { good: 'Chintz Fabrics', origin: 'Coromandel Coast', value: 'Painted Cotton', info: 'Hand-painted and resist-dyed cotton, exported globally' },
        { good: 'Indigo Dye', origin: 'Gujarat & Bengal', value: 'Blue Gold', info: 'Natural blue dye that revolutionized textile industries' },
        { good: 'Silk Brocade', origin: 'Varanasi & Kanchipuram', value: 'Luxury Textile', info: 'Intricately woven silk with gold and silver threads' }
      ]
    },
    {
      name: 'Precious Materials',
      icon: '💎',
      items: [
        { good: 'Diamonds', origin: 'Golconda, Deccan', value: 'Rarest Gems', info: 'India was the only source of diamonds until the 18th century' },
        { good: 'Pearls', origin: 'Tamil Coast & Persian Gulf', value: 'Ocean Jewels', info: 'Natural pearls from Indian waters adorned royalty worldwide' },
        { good: 'Ivory', origin: 'Indian Forests', value: 'White Gold', info: 'Carved into intricate art pieces and luxury items' },
        { good: 'Precious Stones', origin: 'Various Indian Regions', value: 'Gemstone Treasury', info: 'Rubies, sapphires, emeralds from Indian mines' }
      ]
    },
    {
      name: 'Medicinal & Aromatic',
      icon: '⚕️',
      items: [
        { good: 'Sandalwood', origin: 'Mysore & Deccan', value: 'Sacred Wood', info: 'Used in perfumes, medicine, and religious ceremonies' },
        { good: 'Ayurvedic Herbs', origin: 'All Regions of India', value: 'Ancient Medicine', info: 'Medicinal plants and formulations exported for healing' },
        { good: 'Camphor', origin: 'Southern India', value: 'Purifying Substance', info: 'Used in religious rituals and traditional medicine' },
        { good: 'Betel Nuts & Leaves', origin: 'Malabar & Assam', value: 'Social Currency', info: 'Important in social and ceremonial exchanges' }
      ]
    },
    {
      name: 'Metals & Crafts',
      icon: '⚒️',
      items: [
        { good: 'Wootz Steel', origin: 'Southern India', value: 'Superior Metal', info: 'Legendary Damascus steel originated from Indian crucible steel' },
        { good: 'Bronze Sculptures', origin: 'Chola Kingdom', value: 'Divine Art', info: 'Exquisite bronze icons of deities, exported as art and devotion' },
        { good: 'Brass & Copper Ware', origin: 'North India', value: 'Essential Goods', info: 'Utilitarian and decorative metalwork' },
        { good: 'Carved Ivory', origin: 'Various Regions', value: 'Luxury Craft', info: 'Intricate carvings and decorative pieces for wealthy patrons' }
      ]
    }
  ];

  return (
    <div>
      <div className="ancient-scroll mb-8">
        <h2 className="text-3xl font-bold mb-4 text-amber-900">
          📦 Treasures of Indian Commerce
        </h2>
        <p className="text-lg leading-relaxed mb-4">
          Ancient India was renowned throughout the world as a land of incredible wealth and exotic 
          goods. Roman authors wrote with wonder about the spices, gems, and fine textiles that 
          drained their empire's gold reserves. Chinese merchants sought Indian cotton and precious 
          stones, while Arab traders built fortunes on the pepper trade. The commodities listed here 
          represent the goods that made India the economic center of the ancient world.
        </p>
        <p className="text-lg leading-relaxed">
          Many of these goods were available nowhere else on Earth. India's unique climate, 
          skilled craftsmen, and ancient knowledge created products that commanded astronomical 
          prices in foreign markets. The wealth generated by this trade funded great temples, 
          universities, and the flourishing of Indian civilization.
        </p>
      </div>

      <div className="space-y-8">
        {categories.map((category, index) => (
          <div key={index}>
            <div className="flex items-center gap-3 mb-4">
              <span className="text-4xl">{category.icon}</span>
              <h3 className="text-2xl font-bold text-amber-900">{category.name}</h3>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {category.items.map((item, idx) => (
                <div key={idx} className="ancient-card">
                  <div className="flex justify-between items-start mb-2">
                    <h4 className="text-xl font-bold text-amber-900">{item.good}</h4>
                    <span className="ancient-badge text-xs">{item.value}</span>
                  </div>
                  
                  <div className="text-sm mb-2">
                    <span className="font-bold text-amber-800">Origin:</span>{' '}
                    <span className="italic">{item.origin}</span>
                  </div>
                  
                  <p className="text-sm text-gray-700 leading-relaxed">
                    {item.info}
                  </p>
                </div>
              ))}
            </div>

            {index < categories.length - 1 && (
              <div className="ancient-divider my-6"></div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-8 ancient-scroll">
        <h3 className="text-xl font-bold mb-3 text-amber-900">💰 Trade Economics</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
          <div className="p-4 bg-amber-50 rounded border-2 border-amber-200">
            <div className="font-bold text-amber-900 mb-2">Payment Methods</div>
            <p>Gold & silver coins (Roman denarii highly valued), barter systems, bills of exchange, and credit networks through merchant guilds</p>
          </div>
          <div className="p-4 bg-amber-50 rounded border-2 border-amber-200">
            <div className="font-bold text-amber-900 mb-2">Trade Balance</div>
            <p>India enjoyed a massive trade surplus - Roman gold flowed eastward in such quantities that Roman authors complained of wealth drain from their empire</p>
          </div>
          <div className="p-4 bg-amber-50 rounded border-2 border-amber-200">
            <div className="font-bold text-amber-900 mb-2">Merchant Guilds</div>
            <p>Powerful shrenis (guilds) regulated trade, set prices, maintained quality standards, and protected merchant interests across trade routes</p>
          </div>
        </div>
      </div>

      <div className="mt-8 ancient-scroll">
        <h3 className="text-xl font-bold mb-4 text-amber-900">🌍 Global Impact</h3>
        <p className="text-sm leading-relaxed mb-3">
          The demand for Indian goods shaped world history. The Roman drain of gold to India was a 
          major economic concern. The search for direct sea routes to India motivated European 
          exploration in the 15th century. Indian textiles influenced fashion across continents, 
          and Indian spices literally changed the taste of food worldwide.
        </p>
        <p className="text-sm leading-relaxed">
          Beyond material goods, India exported philosophical ideas, mathematical concepts (including 
          the zero), astronomical knowledge, and religious teachings that fundamentally transformed 
          human civilization. The trade routes were also routes of knowledge and culture.
        </p>
      </div>
    </div>
  );
}