/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AncientText {
    id: string;
    sanskritName: string;
    name: string;
    year: string;
    description: string;
    authors: Array<string>;
    relevance: string;
    teachings: Array<string>;
}
export interface TextCitation {
    verse: string;
    textName: string;
    translation: string;
    chapter: string;
}
export interface Technique {
    id: string;
    duration: string;
    doshasAffected: Array<Dosha>;
    sanskritName: string;
    difficulty: string;
    name: string;
    origin: TextCitation;
    scientificBacking: string;
    contraindications: Array<string>;
    steps: Array<string>;
    shortDescription: string;
    category: TechniqueCategory;
    imageKeyword: string;
    relatedTechniqueIds: Array<string>;
    benefits: Array<string>;
    historicalContext: string;
    longDescription: string;
}
export interface FounderInfo {
    bio: string;
    title: string;
    mission: string;
    name: string;
    credentials: Array<string>;
    imageKeyword: string;
}
export interface DoshaDetail {
    imbalanceSymptoms: Array<string>;
    name: string;
    description: string;
    qualities: Array<string>;
}
export enum Dosha {
    Vata = "Vata",
    Pitta = "Pitta",
    Kapha = "Kapha"
}
export enum TechniqueCategory {
    Sattvavajaya = "Sattvavajaya",
    Pranayama = "Pranayama",
    Dhyana = "Dhyana",
    HerbalRemedies = "HerbalRemedies",
    MantraChanting = "MantraChanting",
    Mudra = "Mudra"
}
export interface backendInterface {
    getAllTechniques(): Promise<Array<Technique>>;
    getAncientTexts(): Promise<Array<AncientText>>;
    getDoshaDetails(): Promise<Array<DoshaDetail>>;
    getFounderInfo(): Promise<FounderInfo>;
    getTechniqueById(id: string): Promise<Technique | null>;
    getTechniquesByCategory(category: TechniqueCategory): Promise<Array<Technique>>;
}
import type { Dosha as _Dosha, Technique as _Technique, TechniqueCategory as _TechniqueCategory, TextCitation as _TextCitation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllTechniques(): Promise<Array<Technique>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTechniques();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTechniques();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAncientTexts(): Promise<Array<AncientText>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAncientTexts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAncientTexts();
            return result;
        }
    }
    async getDoshaDetails(): Promise<Array<DoshaDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoshaDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoshaDetails();
            return result;
        }
    }
    async getFounderInfo(): Promise<FounderInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getFounderInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFounderInfo();
            return result;
        }
    }
    async getTechniqueById(arg0: string): Promise<Technique | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechniqueById(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechniqueById(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTechniquesByCategory(arg0: TechniqueCategory): Promise<Array<Technique>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTechniquesByCategory(to_candid_TechniqueCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTechniquesByCategory(to_candid_TechniqueCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Dosha_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dosha): Dosha {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TechniqueCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechniqueCategory): TechniqueCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Technique_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Technique): Technique {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Technique]): Technique | null {
    return value.length === 0 ? null : from_candid_Technique_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: string;
    doshasAffected: Array<_Dosha>;
    sanskritName: string;
    difficulty: string;
    name: string;
    origin: _TextCitation;
    scientificBacking: string;
    contraindications: Array<string>;
    steps: Array<string>;
    shortDescription: string;
    category: _TechniqueCategory;
    imageKeyword: string;
    relatedTechniqueIds: Array<string>;
    benefits: Array<string>;
    historicalContext: string;
    longDescription: string;
}): {
    id: string;
    duration: string;
    doshasAffected: Array<Dosha>;
    sanskritName: string;
    difficulty: string;
    name: string;
    origin: TextCitation;
    scientificBacking: string;
    contraindications: Array<string>;
    steps: Array<string>;
    shortDescription: string;
    category: TechniqueCategory;
    imageKeyword: string;
    relatedTechniqueIds: Array<string>;
    benefits: Array<string>;
    historicalContext: string;
    longDescription: string;
} {
    return {
        id: value.id,
        duration: value.duration,
        doshasAffected: from_candid_vec_n4(_uploadFile, _downloadFile, value.doshasAffected),
        sanskritName: value.sanskritName,
        difficulty: value.difficulty,
        name: value.name,
        origin: value.origin,
        scientificBacking: value.scientificBacking,
        contraindications: value.contraindications,
        steps: value.steps,
        shortDescription: value.shortDescription,
        category: from_candid_TechniqueCategory_n7(_uploadFile, _downloadFile, value.category),
        imageKeyword: value.imageKeyword,
        relatedTechniqueIds: value.relatedTechniqueIds,
        benefits: value.benefits,
        historicalContext: value.historicalContext,
        longDescription: value.longDescription
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Vata: null;
} | {
    Pitta: null;
} | {
    Kapha: null;
}): Dosha {
    return "Vata" in value ? Dosha.Vata : "Pitta" in value ? Dosha.Pitta : "Kapha" in value ? Dosha.Kapha : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sattvavajaya: null;
} | {
    Pranayama: null;
} | {
    Dhyana: null;
} | {
    HerbalRemedies: null;
} | {
    MantraChanting: null;
} | {
    Mudra: null;
}): TechniqueCategory {
    return "Sattvavajaya" in value ? TechniqueCategory.Sattvavajaya : "Pranayama" in value ? TechniqueCategory.Pranayama : "Dhyana" in value ? TechniqueCategory.Dhyana : "HerbalRemedies" in value ? TechniqueCategory.HerbalRemedies : "MantraChanting" in value ? TechniqueCategory.MantraChanting : "Mudra" in value ? TechniqueCategory.Mudra : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Technique>): Array<Technique> {
    return value.map((x)=>from_candid_Technique_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Dosha>): Array<Dosha> {
    return value.map((x)=>from_candid_Dosha_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TechniqueCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechniqueCategory): _TechniqueCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechniqueCategory): {
    Sattvavajaya: null;
} | {
    Pranayama: null;
} | {
    Dhyana: null;
} | {
    HerbalRemedies: null;
} | {
    MantraChanting: null;
} | {
    Mudra: null;
} {
    return value == TechniqueCategory.Sattvavajaya ? {
        Sattvavajaya: null
    } : value == TechniqueCategory.Pranayama ? {
        Pranayama: null
    } : value == TechniqueCategory.Dhyana ? {
        Dhyana: null
    } : value == TechniqueCategory.HerbalRemedies ? {
        HerbalRemedies: null
    } : value == TechniqueCategory.MantraChanting ? {
        MantraChanting: null
    } : value == TechniqueCategory.Mudra ? {
        Mudra: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
