/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AncientText {
  'id' : string,
  'sanskritName' : string,
  'name' : string,
  'year' : string,
  'description' : string,
  'authors' : Array<string>,
  'relevance' : string,
  'teachings' : Array<string>,
}
export type Dosha = { 'Vata' : null } |
  { 'Pitta' : null } |
  { 'Kapha' : null };
export interface DoshaDetail {
  'imbalanceSymptoms' : Array<string>,
  'name' : string,
  'description' : string,
  'qualities' : Array<string>,
}
export interface FounderInfo {
  'bio' : string,
  'title' : string,
  'mission' : string,
  'name' : string,
  'credentials' : Array<string>,
  'imageKeyword' : string,
}
export interface Technique {
  'id' : string,
  'duration' : string,
  'doshasAffected' : Array<Dosha>,
  'sanskritName' : string,
  'difficulty' : string,
  'name' : string,
  'origin' : TextCitation,
  'scientificBacking' : string,
  'contraindications' : Array<string>,
  'steps' : Array<string>,
  'shortDescription' : string,
  'category' : TechniqueCategory,
  'imageKeyword' : string,
  'relatedTechniqueIds' : Array<string>,
  'benefits' : Array<string>,
  'historicalContext' : string,
  'longDescription' : string,
}
export type TechniqueCategory = { 'Sattvavajaya' : null } |
  { 'Pranayama' : null } |
  { 'Dhyana' : null } |
  { 'HerbalRemedies' : null } |
  { 'MantraChanting' : null } |
  { 'Mudra' : null };
export interface TextCitation {
  'verse' : string,
  'textName' : string,
  'translation' : string,
  'chapter' : string,
}
export interface _SERVICE {
  'getAllTechniques' : ActorMethod<[], Array<Technique>>,
  'getAncientTexts' : ActorMethod<[], Array<AncientText>>,
  'getDoshaDetails' : ActorMethod<[], Array<DoshaDetail>>,
  'getFounderInfo' : ActorMethod<[], FounderInfo>,
  'getTechniqueById' : ActorMethod<[string], [] | [Technique]>,
  'getTechniquesByCategory' : ActorMethod<
    [TechniqueCategory],
    Array<Technique>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];