/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Dosha = IDL.Variant({
  'Vata' : IDL.Null,
  'Pitta' : IDL.Null,
  'Kapha' : IDL.Null,
});
export const TextCitation = IDL.Record({
  'verse' : IDL.Text,
  'textName' : IDL.Text,
  'translation' : IDL.Text,
  'chapter' : IDL.Text,
});
export const TechniqueCategory = IDL.Variant({
  'Sattvavajaya' : IDL.Null,
  'Pranayama' : IDL.Null,
  'Dhyana' : IDL.Null,
  'HerbalRemedies' : IDL.Null,
  'MantraChanting' : IDL.Null,
  'Mudra' : IDL.Null,
});
export const Technique = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Text,
  'doshasAffected' : IDL.Vec(Dosha),
  'sanskritName' : IDL.Text,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'origin' : TextCitation,
  'scientificBacking' : IDL.Text,
  'contraindications' : IDL.Vec(IDL.Text),
  'steps' : IDL.Vec(IDL.Text),
  'shortDescription' : IDL.Text,
  'category' : TechniqueCategory,
  'imageKeyword' : IDL.Text,
  'relatedTechniqueIds' : IDL.Vec(IDL.Text),
  'benefits' : IDL.Vec(IDL.Text),
  'historicalContext' : IDL.Text,
  'longDescription' : IDL.Text,
});
export const AncientText = IDL.Record({
  'id' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'authors' : IDL.Vec(IDL.Text),
  'relevance' : IDL.Text,
  'teachings' : IDL.Vec(IDL.Text),
});
export const DoshaDetail = IDL.Record({
  'imbalanceSymptoms' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'qualities' : IDL.Vec(IDL.Text),
});
export const FounderInfo = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'mission' : IDL.Text,
  'name' : IDL.Text,
  'credentials' : IDL.Vec(IDL.Text),
  'imageKeyword' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
  'getAncientTexts' : IDL.Func([], [IDL.Vec(AncientText)], ['query']),
  'getDoshaDetails' : IDL.Func([], [IDL.Vec(DoshaDetail)], ['query']),
  'getFounderInfo' : IDL.Func([], [FounderInfo], ['query']),
  'getTechniqueById' : IDL.Func([IDL.Text], [IDL.Opt(Technique)], ['query']),
  'getTechniquesByCategory' : IDL.Func(
      [TechniqueCategory],
      [IDL.Vec(Technique)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Dosha = IDL.Variant({
    'Vata' : IDL.Null,
    'Pitta' : IDL.Null,
    'Kapha' : IDL.Null,
  });
  const TextCitation = IDL.Record({
    'verse' : IDL.Text,
    'textName' : IDL.Text,
    'translation' : IDL.Text,
    'chapter' : IDL.Text,
  });
  const TechniqueCategory = IDL.Variant({
    'Sattvavajaya' : IDL.Null,
    'Pranayama' : IDL.Null,
    'Dhyana' : IDL.Null,
    'HerbalRemedies' : IDL.Null,
    'MantraChanting' : IDL.Null,
    'Mudra' : IDL.Null,
  });
  const Technique = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Text,
    'doshasAffected' : IDL.Vec(Dosha),
    'sanskritName' : IDL.Text,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'origin' : TextCitation,
    'scientificBacking' : IDL.Text,
    'contraindications' : IDL.Vec(IDL.Text),
    'steps' : IDL.Vec(IDL.Text),
    'shortDescription' : IDL.Text,
    'category' : TechniqueCategory,
    'imageKeyword' : IDL.Text,
    'relatedTechniqueIds' : IDL.Vec(IDL.Text),
    'benefits' : IDL.Vec(IDL.Text),
    'historicalContext' : IDL.Text,
    'longDescription' : IDL.Text,
  });
  const AncientText = IDL.Record({
    'id' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'authors' : IDL.Vec(IDL.Text),
    'relevance' : IDL.Text,
    'teachings' : IDL.Vec(IDL.Text),
  });
  const DoshaDetail = IDL.Record({
    'imbalanceSymptoms' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'qualities' : IDL.Vec(IDL.Text),
  });
  const FounderInfo = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'mission' : IDL.Text,
    'name' : IDL.Text,
    'credentials' : IDL.Vec(IDL.Text),
    'imageKeyword' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllTechniques' : IDL.Func([], [IDL.Vec(Technique)], ['query']),
    'getAncientTexts' : IDL.Func([], [IDL.Vec(AncientText)], ['query']),
    'getDoshaDetails' : IDL.Func([], [IDL.Vec(DoshaDetail)], ['query']),
    'getFounderInfo' : IDL.Func([], [FounderInfo], ['query']),
    'getTechniqueById' : IDL.Func([IDL.Text], [IDL.Opt(Technique)], ['query']),
    'getTechniquesByCategory' : IDL.Func(
        [TechniqueCategory],
        [IDL.Vec(Technique)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };